### ISSUE TITLE
Cannot install on W11 using pip

### ISSUE THREAD

**Issue by tlegoc** [fbertola/bgfx-python#27]
Trying `pip install bgfx-python`, got this error.

```
Collecting bgfx-python
  Downloading bgfx-python-2.0.1.tar.gz (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\theo\AppData\Local\Temp\pip-install-6n34c31u\bgfx-python_60beba566d694e83886ef64708c08b88\setup.py", line 7, in <module>
          from skbuild import setup
      ModuleNotFoundError: No module named 'skbuild'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.```

Might be a problem with modules, I don't know what skbuild is but it's not finding it.

**Comment by stuaxo** [comment]
The same issue occur on Ubuntu, 20.22, 64 bit, with python 3.10, so it's not a Windows issue.

**Comment by stuaxo** [comment]
The issue on Ubuntu is that we're on python 3.10, and the packaged versions only go up to 3.9, so it's trying to install from the .tar.gz

@tlegoc can you try and reinstall using -v - that will show some more info, including what is being installed.

`pip install bgfx-python -v`

**Comment by mfaizsyahmi** [comment]
Same issue. Win10, Py 3.11, skbuild module not found.

**Comment by robotnetwerk** [comment]
fixing the skbuild not found :

pip install scikit-build

but then the next thing is not working, it can not build yet....
```
(.venv) PS C:\Users\panda\Desktop\pythonProjectIMGUI> C:\Users\panda\Desktop\pythonProjectIMGUI\.venv\Scripts\pip3.exe install bgfx-python -v                                                                   
Using pip 23.3.2 from C:\Users\panda\Desktop\pythonProjectIMGUI\.venv\Lib\site-packages\pip (python 3.12)
Collecting bgfx-python
  Using cached bgfx-python-2.0.1.tar.gz (10 kB)
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "C:\Users\panda\Desktop\pythonProjectIMGUI\.venv\Lib\site-packages\skbuild\setuptools_wrap.py", line 453, in setup
      _check_skbuild_parameters(cmake_install_dir, cmake_source_dir)
    File "C:\Users\panda\Desktop\pythonProjectIMGUI\.venv\Lib\site-packages\skbuild\setuptools_wrap.py", line 282, in _check_skbuild_parameters
      raise SKBuildError(msg)


    setup parameter 'cmake_source_dir' set to a nonexistent directory.
      Project Root  : C:\Users\panda\AppData\Local\Temp\pip-install-litn3c9y\bgfx-python_880abe3ad8b647618bf01be3e5c1a067
      CMake Source Directory: src

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\panda\Desktop\pythonProjectIMGUI\.venv\Scripts\python.exe' -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'C:\\Users\\panda\\AppData\\Local\\Temp\\pip-install-litn3c9y\\bgfx-python_880abe3ad8b647618bf01be3e5c1a067\\setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base 'C:\Users\panda\AppData\Local\Temp\pip-pip-egg-info-ikdbdc3u'
  cwd: C:\Users\panda\AppData\Local\Temp\pip-install-litn3c9y\bgfx-python_880abe3ad8b647618bf01be3e5c1a067\
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by ilulillirillion** [comment]
Same exact issue (down to getting the non-existent src dir if trying to bypass by install scikit-build directly) when attempting to get this installed on macos. bgfx has been a nightmare in total, third language we've tried to get it going with.
